### ISSUE TITLE
/OSweep/lookups/greynoise_feed.csv missing

### ISSUE THREAD

**Issue by soufianetahiri** [ecstatic-nobel/osweep#7]
First of all thanks for the great work.

Tested on ubuntu and on centos, both install cannot get GreyNoise working.

 command="greynoise", Error: Traceback (most recent call last): File "/opt/splunk/etc/apps/OSweep/bin/commons.py", line 84, in return_results new_results = module.process_iocs(None) File "/opt/splunk/etc/apps/OSweep/bin/greynoise.py", line 127, in process_iocs open_file = open("{}/greynoise_feed.csv".format(lookup_path), "r") IOError: [Errno 2] No such file or directory: '/opt/splunk/etc/apps/OSweep/lookups/greynoise_feed.csv'

**Comment by kiraitachi** [comment]
Already had opened a case about this on December 2019:

https://github.com/ecstatic-nobel/OSweep/issues/5

Not much said, but check the thread.

> First of all thanks for the great work.
> 
> Tested on ubuntu and on centos, both install cannot get GreyNoise working.
> 
> command="greynoise", Error: Traceback (most recent call last): File "/opt/splunk/etc/apps/OSweep/bin/commons.py", line 84, in return_results new_results = module.process_iocs(None) File "/opt/splunk/etc/apps/OSweep/bin/greynoise.py", line 127, in process_iocs open_file = open("{}/greynoise_feed.csv".format(lookup_path), "r") IOError: [Errno 2] No such file or directory: '/opt/splunk/etc/apps/OSweep/lookups/greynoise_feed.csv'
